### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by BMPMS** [serge-web/map#1]
Need to establish which icons the client wants to use and whether we need to commission custom icons.

**Comment by BMPMS** [comment]
Hi there.

I've switch to your SVG icons.  The only downside of this is you can't give them a 'fill' which is a nice feature with font awesome.  I'm sure there is a way to do this but it's not my area!

**Comment by IanMayo** [comment]
Some have fills, here's fishing_vessel:

![image](https://user-images.githubusercontent.com/1108513/54217935-72c11700-44e4-11e9-9b09-57c378590e2f.png)

**Comment by BMPMS** [comment]
Yes, but as I'm appending it as an image it is fixed so you can assign the fill - or I haven't worked out how to do it.

Font Awesome/Linear Icons approach you append to a text element with the "/u" reference as the text which somehow allows you to do this.

**Comment by IanMayo** [comment]
ok, these are all custom created, from a set of PPT slides provided by MWC for the Debrief app.

It won't be a surprise if we don't follow any wider standards.  Once we know about the wider standards we can adopt them.

BTW - could you show me how the above Fishing Vessel svg appears in the Serge map?

**Comment by IanMayo** [comment]
I think there's still an icon offset issue:
![image](https://user-images.githubusercontent.com/1108513/54363069-11bf4d80-4662-11e9-8a7a-7dd9d474aac6.png)

In the SVG icons from the zip file, the red circle marks the `origin` of the SVG - so that point would be in the centre of the cell, I guess.
