### ISSUE TITLE
Possible bug in planned route

### ISSUE THREAD

**Issue by IanMayo** [serge-web/map#14]
There may be a bug in the route-planning document:
![image](https://user-images.githubusercontent.com/1108513/54043902-98d57700-41c5-11e9-8ee8-95e66a85a21b.png)

I would expect step 1 to be `27-18 to 27-19 speed 4`

**Comment by BMPMS** [comment]
Hi…

I don’t think I’ve been very clear about my understanding of speed ?!?

My logic goes as follows:  

* each turn has a total_moves (documentation says 18 but can be changeable)
* before a turn starts, potential speeds for each group are calculated and a hex_speed is defined

speed 1 = fastest, icon moves every step (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
speed 2 = slower, icon moves every 2 steps (2,4,6,8,10,12,14,16,18)
speed 3 = even slower, icon moves every 3 steps (3,6,9,12,15,18)

If a player changes a speed of a group, then the speed and therefore steps changes.  Up to a maximum of total_moves (currently 18).

Clearer?  Have I totally misunderstood?   The time a step represents and the distance per hour each speed represents can be entered if needed before a turn starts and shown as a variable.  There are various other bits of data stored in moves (see json test data) and any amount more can be added.

**Comment by IanMayo** [comment]
I'm ok with the speed,  but if the first row represents where the ship moves in this step, I would expect it to move `from` 27-18 `to` 27-19.  But, row one has the same cell twice.

(replying next week is fine).

**Comment by BMPMS** [comment]
Oh yes… Must be a typo in the code.  Will fix Monday.
