### ISSUE TITLE
Minor coordinate issue

### ISSUE THREAD

**Issue by IanMayo** [serge-web/map#19]
This is really minor...

When we're drawing the line through a route, I don't think we're quite going through the centre of the cell.  There's some _wiggle_ in the lines drawn here:
![image](https://user-images.githubusercontent.com/1108513/54424985-1f311200-470c-11e9-92bd-0aa734e1ec9e.png)

**Comment by BMPMS** [comment]
![Screen Shot 2019-03-15 at 13 26 26](https://user-images.githubusercontent.com/18613602/54435962-92954c80-4729-11e9-83f7-680b181ee7c5.png)
Even hex centers were a bit off.  I've now fixed it and reorganised the code so a bit better.

Red circles there for you to double check - ping when ok to remove?

Although maybe we do want to mark the start of a journey in some way ??

**Comment by IanMayo** [comment]
Yes, the centres are fine.

I think that by eye we can follow the route line back to it's starting point.  So, that's how the start of the journey is marked.

**Comment by BMPMS** [comment]
Circles removed then..
