### ISSUE TITLE
Tooltips/In Map information

### ISSUE THREAD

**Issue by BMPMS** [serge-web/map#3]
Think about what information might be available when interacting with the map - ie tooltips.

**Comment by BMPMS** [comment]
Re: confirming the hex's and their position (long/lat)  I could add a tooltip or have a separate panel (like zoom/moves) which changed on mouseover?

**Comment by IanMayo** [comment]
I suspect it may be a pain repeatedly waiting the second or so for the tooltip to appear.

A toggle mode for displaying the cell reference inside the cell would seem the ideal solution for debugging cell reference issues / verifying coordinates.

But, displaying the `current cell` in a side panel would deliver the same capability.

**Comment by BMPMS** [comment]
Either fine with me.  Or I guess you could be smart and only show it when at a certain zoom level? Tooltips tend to be pretty instant but could also get in the way.

**Comment by IanMayo** [comment]
We just spoke.  We agreed that we would show hex coordinates and lat/long in the cell.  In the future we _may_ wish to also show the other characteristics for that cell.

I'm happy for you to decide on a scale/zoom level beneath which the above isn't shown, if necessary.
