### ISSUE TITLE
Hex Type

### ISSUE THREAD

**Issue by BMPMS** [serge-web/map#7]
Need to get clarification from client as to what each type represents, whether we've got the colours right and which vessels can/can't move onto certain types..

**Comment by IanMayo** [comment]
> which vessels can/can't move onto certain types

Hmm, are you starting to think about obstacle avoidance?

https://www.redblobgames.com/grids/hexagons/#range-obstacles

You're right, the "state of the world" message would have to include whether they can pass land or not.
