### ISSUE TITLE
Pan_Zoom_Functionality

### ISSUE THREAD

**Issue by BMPMS** [serge-web/map#8]
It's quite likely that a wargame that covers 6 weeks of operations will cover a large body of water.

But, when planning happens for 24 hour steps, the planning will be conducted at relatively small scale.

So, for users to be able to view the whole map, and work the detail of small hex squares, we should introduce the ability to pan/zoom around the map.

At the large table-top panel, even relatively small cells may still be large enough to work on.  But, if one for is represented by a single user at a laptop, and that player is performing the map role and the comms role, it's likely that the player will need to zoom in on the map in order to interact with it.

As discussed previously, it is a strategic objective of the client to demonstrate the table-top monitors in active use.  Flashy pan/zoom will be effective in meeting that objective.

**Comment by BMPMS** [comment]
Yes, understood @IanMayo.  I'm just leaving it till last on my list as it is an added complication to juggle in the head.  I have made sure that all reference to screen positions is in one function (get_points) so when it comes to adding the pan/zoom etc it will be super solid to implement.

Did you want to add zoom in/out and reset buttons somewhere?  Possibly HTML again but I can add a separate svg for now if you want?

**Comment by IanMayo** [comment]
Yes for zoom  in/out & fit-to-window please.  Handling is an SVG outline would be fine for now.
